# Generated by Django 5.1.3 on 2025-02-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinaryservice',
            name='service_type',
            field=models.CharField(choices=[('vaccination', 'Vaccination'), ('checkup', 'General Checkup'), ('surgery', 'Surgery'), ('dental', 'Dental Care'), ('grooming', 'Grooming')], max_length=50),
        ),
    ]
